# Generated by Django 4.1.1 on 2023-01-19 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("name_ar", models.CharField(max_length=150, verbose_name="name_ar")),
                ("description", models.TextField(verbose_name="description")),
                ("description_ar", models.TextField(verbose_name="description_ar")),
                ("image", models.ImageField(upload_to="images/", verbose_name="image")),
                ("job", models.CharField(max_length=150, verbose_name="job")),
                ("job_ar", models.CharField(max_length=150, verbose_name="job_ar")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("phone", models.CharField(max_length=15, verbose_name="phone")),
                ("address", models.CharField(max_length=150, verbose_name="address")),
                (
                    "address_ar",
                    models.CharField(max_length=150, verbose_name="address_ar"),
                ),
                ("facebook", models.URLField(verbose_name="facebook")),
                ("github", models.URLField(verbose_name="github")),
                ("whatsapp", models.CharField(max_length=15, verbose_name="whatsapp")),
                ("linkedin", models.URLField(verbose_name="linkedin")),
                (
                    "Resume",
                    models.FileField(upload_to="resumes/", verbose_name="Resume"),
                ),
            ],
            options={
                "verbose_name_plural": "About Me",
            },
        ),
        migrations.CreateModel(
            name="Certifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/", verbose_name="image")),
            ],
            options={
                "verbose_name_plural": "Certifications",
            },
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Course Title"),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=150, verbose_name="Course Title Arabic"
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(verbose_name="Course Description Arabic"),
                ),
                ("poster", models.ImageField(upload_to="courses/posters/")),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Course language"
                    ),
                ),
                (
                    "language_ar",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Course language Arabic",
                    ),
                ),
                ("description", models.TextField(verbose_name="Course Description")),
                ("started_at", models.DateField(verbose_name="Started At")),
                ("ended_at", models.DateField(verbose_name="Ended At")),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Course price"
                    ),
                ),
                (
                    "discount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Course Discount for Price"
                    ),
                ),
                (
                    "price_after_discount",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        verbose_name="Course Price After Discount",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=100, verbose_name="project_name"),
                ),
                (
                    "project_name_ar",
                    models.CharField(max_length=100, verbose_name="project_name_ar"),
                ),
                ("category", models.CharField(max_length=50, verbose_name="category")),
                (
                    "category_ar",
                    models.CharField(max_length=50, verbose_name="category_ar"),
                ),
                ("client", models.CharField(max_length=50, verbose_name="client")),
                (
                    "client_ar",
                    models.CharField(max_length=50, verbose_name="client_ar"),
                ),
                ("project_date", models.DateField(verbose_name="project_date")),
                ("project_url", models.URLField(verbose_name="project_url")),
                (
                    "project_image",
                    models.ImageField(
                        upload_to="images/", verbose_name="project_image"
                    ),
                ),
                ("project_desc", models.TextField(verbose_name="project_desc")),
                ("project_desc_ar", models.TextField(verbose_name="project_desc_ar")),
            ],
            options={
                "verbose_name_plural": "Portfolio",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("title_ar", models.CharField(max_length=50, verbose_name="title_ar")),
                ("description", models.TextField(verbose_name="description")),
                ("description_ar", models.TextField(verbose_name="description_ar")),
                ("icon", models.CharField(max_length=50, verbose_name="icon")),
            ],
            options={
                "verbose_name_plural": "Service",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("rate", models.IntegerField(default=0, verbose_name="rate")),
            ],
            options={
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("title_ar", models.CharField(max_length=50, verbose_name="title_ar")),
                ("number", models.IntegerField(verbose_name="number")),
                ("icon", models.CharField(max_length=50, verbose_name="icon")),
            ],
            options={
                "verbose_name_plural": "Statistics",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("name_ar", models.CharField(max_length=50, verbose_name="name_ar")),
                ("job", models.CharField(max_length=50, verbose_name="job")),
                ("job_ar", models.CharField(max_length=50, verbose_name="job_ar")),
                ("image", models.ImageField(upload_to="images/", verbose_name="image")),
                ("description", models.TextField(verbose_name="description")),
                ("description_ar", models.TextField(verbose_name="description_ar")),
            ],
            options={
                "verbose_name_plural": "Testimonial",
            },
        ),
        migrations.CreateModel(
            name="ProjectImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="project_images/", verbose_name="image"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ProjectImages",
            },
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                ("title_ar", models.CharField(max_length=150, verbose_name="title_ar")),
                (
                    "jobs_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.aboutme",
                        verbose_name="jobs_for",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Jobs",
            },
        ),
        migrations.CreateModel(
            name="Courses_Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Course Video Title"),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=150, verbose_name="Course Video Title Arabic"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=100, verbose_name="Course Video Description"
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(
                        max_length=100, verbose_name="Course Video Description Arabic"
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        upload_to="courses/Videos/Posters/", verbose_name="poster"
                    ),
                ),
                (
                    "video",
                    models.FileField(upload_to="courses/Videos/", verbose_name="Video"),
                ),
                (
                    "video_duration_in_min",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Video Duration in Minutes ?"
                    ),
                ),
                (
                    "video_number",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Video Number ?"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.courses",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Courses Videos",
            },
        ),
        migrations.CreateModel(
            name="Course_Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("user_name", models.CharField(max_length=100, verbose_name="User")),
                ("comment", models.CharField(max_length=200, verbose_name="Comment")),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.courses",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Course Reviews",
            },
        ),
        migrations.CreateModel(
            name="Course_Requirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requirement",
                    models.CharField(
                        max_length=150, verbose_name="Course Benefit item"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.courses",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Course Requirements",
            },
        ),
        migrations.CreateModel(
            name="Course_Lectures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150, verbose_name="Course Lectures Title"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        max_length=150, verbose_name="Course Lectures Title Arabic"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Course Lectures Description"),
                ),
                (
                    "description_ar",
                    models.TextField(verbose_name="Course Lectures Description Arabic"),
                ),
                (
                    "content_in_pdf",
                    models.FileField(
                        upload_to="courses/content_pdfs/", verbose_name="content in pdf"
                    ),
                ),
                (
                    "Content_number",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Content number ?"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.courses",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Courses Lectures",
            },
        ),
        migrations.CreateModel(
            name="Course_Benefits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "benefit",
                    models.CharField(
                        max_length=150, verbose_name="Course Benefit item"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.courses",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Courses Benefits",
            },
        ),
    ]
