# Generated by Django 4.1.1 on 2022-09-05 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("name_ar", models.CharField(max_length=150, verbose_name="name_ar")),
                ("description", models.TextField(verbose_name="description")),
                ("description_ar", models.TextField(verbose_name="description_ar")),
                ("image", models.ImageField(upload_to="images/", verbose_name="image")),
                ("job", models.CharField(max_length=150, verbose_name="job")),
                ("job_ar", models.CharField(max_length=150, verbose_name="job_ar")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("phone", models.CharField(max_length=15, verbose_name="phone")),
                ("address", models.CharField(max_length=150, verbose_name="address")),
                (
                    "address_ar",
                    models.CharField(max_length=150, verbose_name="address_ar"),
                ),
                ("facebook", models.URLField(verbose_name="facebook")),
                ("github", models.URLField(verbose_name="github")),
                ("whatsapp", models.CharField(max_length=15, verbose_name="whatsapp")),
                ("linkedin", models.URLField(verbose_name="linkedin")),
                (
                    "Resume",
                    models.FileField(upload_to="resumes/", verbose_name="Resume"),
                ),
            ],
            options={"verbose_name_plural": "About Me",},
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("title_ar", models.CharField(max_length=100, verbose_name="title_ar")),
                ("image", models.ImageField(upload_to="images/", verbose_name="image")),
                ("description", models.TextField(verbose_name="description")),
                ("description_ar", models.TextField(verbose_name="description_ar")),
                ("category", models.CharField(max_length=50, verbose_name="category")),
            ],
            options={"verbose_name_plural": "Blog",},
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=100, verbose_name="project_name"),
                ),
                (
                    "project_name_ar",
                    models.CharField(max_length=100, verbose_name="project_name_ar"),
                ),
                ("category", models.CharField(max_length=50, verbose_name="category")),
                (
                    "category_ar",
                    models.CharField(max_length=50, verbose_name="category_ar"),
                ),
                ("client", models.CharField(max_length=50, verbose_name="client")),
                (
                    "client_ar",
                    models.CharField(max_length=50, verbose_name="client_ar"),
                ),
                ("project_date", models.DateField(verbose_name="project_date")),
                ("project_url", models.URLField(verbose_name="project_url")),
                (
                    "project_image",
                    models.ImageField(
                        upload_to="images/", verbose_name="project_image"
                    ),
                ),
                ("project_desc", models.TextField(verbose_name="project_desc")),
                ("project_desc_ar", models.TextField(verbose_name="project_desc_ar")),
            ],
            options={"verbose_name_plural": "Portfolio",},
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("title_ar", models.CharField(max_length=50, verbose_name="title_ar")),
                ("description", models.TextField(verbose_name="description")),
                ("description_ar", models.TextField(verbose_name="description_ar")),
                ("icon", models.CharField(max_length=50, verbose_name="icon")),
            ],
            options={"verbose_name_plural": "Service",},
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("rate", models.IntegerField(default=0, verbose_name="rate")),
            ],
            options={"verbose_name_plural": "Skills",},
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("title_ar", models.CharField(max_length=50, verbose_name="title_ar")),
                ("number", models.IntegerField(verbose_name="number")),
                ("icon", models.CharField(max_length=50, verbose_name="icon")),
            ],
            options={"verbose_name_plural": "Statistics",},
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("name_ar", models.CharField(max_length=50, verbose_name="name_ar")),
                ("job", models.CharField(max_length=50, verbose_name="job")),
                ("job_ar", models.CharField(max_length=50, verbose_name="job_ar")),
                ("image", models.ImageField(upload_to="images/", verbose_name="image")),
                ("description", models.TextField(verbose_name="description")),
                ("description_ar", models.TextField(verbose_name="description_ar")),
            ],
            options={"verbose_name_plural": "Testimonial",},
        ),
        migrations.CreateModel(
            name="ProjectImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="project_images/", verbose_name="image"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={"verbose_name_plural": "ProjectImages",},
        ),
    ]
