# Generated by Django 4.1.1 on 2022-09-05 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                ("title_ar", models.CharField(max_length=150, verbose_name="title_ar")),
                (
                    "jobs_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.aboutme",
                        verbose_name="jobs_for",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Jobs",},
        ),
    ]
