# Generated by Django 4.1.1 on 2023-01-19 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_new_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course_Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=300, verbose_name="task")),
                (
                    "task_number",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="task number ?"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.courses",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Course Homework",
            },
        ),
        migrations.DeleteModel(
            name="New_Model",
        ),
    ]
