# Generated by Django 4.1.1 on 2022-09-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category_ar",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="category_ar"
            ),
        ),
    ]
