# Generated by Django 4.1.1 on 2023-01-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_course_homework_delete_new_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_reviews",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date published"
            ),
        ),
    ]
