# Generated by Django 4.1.1 on 2022-09-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_blog_category_ar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/", verbose_name="image")),
            ],
            options={"verbose_name_plural": "Certifications",},
        ),
        migrations.DeleteModel(name="Blog",),
    ]
