# Generated by Django 4.1.1 on 2023-01-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_course_reviews_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_reviews",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=1,
                verbose_name="Rating",
            ),
        ),
    ]
