# Generated by Django 4.1.1 on 2023-01-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_alter_course_reviews_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_reviews",
            name="comment",
            field=models.TextField(verbose_name="Comment"),
        ),
    ]
