# Generated by Django 4.1.1 on 2023-01-22 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portfolio", "0006_alter_course_reviews_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="full_name"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="address"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="students/", verbose_name="image"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="phone"
                    ),
                ),
                (
                    "join_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="join_on"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="username",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Students",
            },
        ),
    ]
