# Generated by Django 4.1.1 on 2023-01-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_cart_courseorder_cartcourse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseorder",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="courseorder",
            name="first_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="courseorder",
            name="last_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="courseorder",
            name="payment_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
