# Generated by Django 4.1.1 on 2023-01-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_remove_cart_student_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseorder",
            name="payment_mode",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
