# Generated by Django 4.1.1 on 2023-01-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_courseorder_payment_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseorder",
            name="ordered_by",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
