# Generated by Django 4.1.1 on 2023-01-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_remove_courseorder_ordered_by_courseorder_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseorder",
            name="payment_completed",
        ),
    ]
